package io.github.zezeg2.aisupport.core.validator;

import io.github.zezeg2.aisupport.common.type.BaseSupportType;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.Map;

/**
 * FeedbackRequest is a class representing a request for providing feedback in a chat-based AI system.
 * <p>
 * This class inherits from the BaseSupportType class and includes additional properties to capture the user input
 * and the output generated by the assistant.
 * <p>
 * The class is annotated with the Lombok annotations @Getter, @Setter, @Builder, and @EqualsAndHashCode(callSuper = true)
 * to automatically generate getter, setter, builder, and equals/hashCode methods, inheriting the behavior from the
 * BaseSupportType class.
 */
@Getter
@Setter
@Builder
@EqualsAndHashCode(callSuper = true)
public class FeedbackRequest extends BaseSupportType {

    /**
     * A map representing the user's input, where each key corresponds to a specific input property, and the associated
     * value represents the input value.
     */
    private Map<String, Object> userInput;

    /**
     * The object representing the output generated by the assistant in response to the user's input.
     */
    private Object assistantOutput;
}
